version: 2.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  hadolint:
    working_directory: ~/repo
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Check Dockerfile
          command: hadolint `find . -type f -name Dockerfile | xargs readlink -f` &> report.json
      - run:
          name: Print Laporan
          command: cat report.json
          when: on_fail
          
  # proses testing aplikasi
  test-app:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependensi
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Menjalankan test
          command: go test -v -short --count=1 $(go list ./...)

  # proses build aplikasi dan push docker images
  build-app-karsajobs:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            ./build_push_image_karsajobs.sh

# Workflows untuk mengatur alur CI Pipeline
workflows:
  ujian-pipeline:
    jobs:
      - hadolint
      - test-app
      - build-app-karsajobs
